name: 'RSI Diff Bot'
description: 'Shows modified states in any changed Robust Station Images.'
branding:
  icon: columns
  color: green
inputs:
  modified:
    description:
      'A list of modified files.'
  removed:
    description:
      'A list of removed files.'
  added:
    description:
      'A list of changed files.'
outputs:
  summary-title:
    description:
      'The title of the RSI diff action.'
  summary-details:
    description:
      'A detailed summary of all the states that changed.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-m'
  - ${{ inputs.modified }}
  - '-r'
  - ${{ inputs.removed }}
  - '-a'
  - ${{ inputs.added }}
